[workspace]
members = ["crates/*"]
resolver = "2"

[profile.debug-opt]
inherits = "release"
debug = 2
debug-assertions = true
incremental = true

[profile.docker]
inherits = "release"
lto = "thin"
strip = "symbols"
