[package]
name = "discord-pls"
description = "discord pls"
authors = ["raykast <me@ryan-s.net>"]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://github.com/ray-kast/the-q/"

[dependencies]
async-trait = "0.1.68"
clap = { version = "4.2.1", features = ["env", "cargo", "derive"] }
dotenv = "0.15.0"
rand = "0.8.5"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
serenity = { workspace = true }
tokio = { version = "1.27.0", features = ["parking_lot", "full", "tracing"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "fmt", "tracing-log"] }
