[package]
name = "paracord"
description = "Helper types for working with Serenity"
authors = ["raykast <me@ryan-s.net>"]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://github.com/ray-kast/the-q/"

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
base64k = { version = "=0.1.0", path = "../base64k" }
chrono = "0.4.24"
ordered-float = "3.6.0"
prost = "0.11.8"
qcore = { version = "0.1.0", path = "../qcore" }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
serenity = { workspace = true }
strsim = "0.10.0"
thiserror = "1.0.40"
tokio = { version = "1.27.0", default-features = false, features = ["sync"] }
tracing = "0.1.37"
url = "2.3.1"
zstd = { version = "0.12.3", features = ["experimental"] }
