[package]
name = "protock"
description = "Tool to check protobuf file compatibility"
authors = ["raykast <me@ryan-s.net>"]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://github.com/ray-kast/the-q/"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive", "cargo"] }
git2 = "0.16.0"
prost = "0.11.6"
prost-types = "0.11.6"
shrec = { version = "0.1.0", path = "../shrec" }
tempfile = "3.3.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["tracing-log", "fmt"] }
