[package]
name = "the-q"
description = "Is he...y’know,"
authors = ["raykast <me@ryan-s.net>"]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://github.com/ray-kast/the-q/"

build = "build.rs"

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.60"
clap = { version = "4.0.32", features = ["env", "cargo", "derive"] }
dotenv = "0.15.0"
futures-util = "0.3.25"
hostname = "0.3.1"
jpeggr = { version = "=0.1.0", path = "../jpeggr" }
notify = "5.1.0"
once_cell = { version = "1.17.0", features = ["parking_lot"] }
ordered-float = "3.4.0"
paracord = { version = "0.1.0", path = "../paracord" }
prost = "0.11.6"
qcore = { version = "0.1.0", path = "../qcore" }
reqwest = { version = "0.11.14", features = ["deflate", "gzip", "brotli", "rustls-tls"], default-features = false }
serenity = { workspace = true }
shrec = { version = "0.1.0", path = "../shrec" }
songbird = { version = "0.3.0", features = ["serenity"] }
strsim = "0.10.0"
tokio = { version = "1.23.0", features = ["parking_lot", "full", "tracing"] }
tracing = "0.1.37"
tracing-loki = { version = "0.2.1", default-features = false, features = ["rustls", "compat-0-2-1"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "fmt", "tracing-log"] }
url = "2.3.1"
walkdir = "2.3.2"

[build-dependencies]
glob = "0.3.1"
prost-build = "0.11.6"
